
version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    container_name: backend_service
    ports:
      - "5050:5050"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    command: node server.js

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
